# Azure deployment script for Vue-Net-Admin-Demo
# Prerequisites: Azure CLI installed and logged in
# Usage: .\infra\deploy.ps1

$ErrorActionPreference = 'Stop'

# Add Azure CLI to PATH
$env:PATH = 'C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin;' + $env:PATH

$ResourceGroup = 'vue-admin-rg'
$Location = 'eastus'
$DeploymentName = 'vue-admin-infra'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Azure Deployment: Vue-Net-Admin-Demo" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# 1. Verify login
Write-Host "[1/6] Verifying Azure login..." -ForegroundColor Yellow
az account show --query '{name:name,id:id}' | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Not logged in. Run: az login" -ForegroundColor Red
    exit 1
}

# 2. Ensure resource group exists
Write-Host "[2/6] Checking resource group..." -ForegroundColor Yellow
$rgExists = az group show --name $ResourceGroup --query id -o tsv 2>$null
if ([string]::IsNullOrWhiteSpace($rgExists)) {
    Write-Host "  Creating resource group '$ResourceGroup' in $Location..." -ForegroundColor Gray
    az group create --name $ResourceGroup --location $Location --tags Environment=dev | Out-Null
    Write-Host "  ✓ Resource group created" -ForegroundColor Green
} else {
    Write-Host "  ✓ Resource group '$ResourceGroup' exists" -ForegroundColor Green
}

# 3. Build Bicep
Write-Host "[3/6] Building Bicep template..." -ForegroundColor Yellow
az bicep build --file "$ScriptDir/main.bicep" | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Bicep build failed" -ForegroundColor Red
    exit 1
}
Write-Host "  ✓ Bicep template compiled" -ForegroundColor Green

# 4. Deploy infrastructure
Write-Host "[4/6] Deploying infrastructure (this takes 5-10 minutes)..." -ForegroundColor Yellow
$deployResult = az deployment group create `
    --resource-group $ResourceGroup `
    --name $DeploymentName `
    --template-file "$ScriptDir/main.bicep" `
    --parameters "$ScriptDir/params.json" `
    --no-parallel `
    --only-show-errors

if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Deployment failed" -ForegroundColor Red
    exit 1
}

# 5. Extract outputs
Write-Host "[5/6] Extracting deployment outputs..." -ForegroundColor Yellow
$outputs = $deployResult | ConvertFrom-Json

$pgPassword = ($outputs | ConvertFrom-Json).properties.pgPasswordGenerated.value
$pgFqdn = ($outputs | ConvertFrom-Json).properties.pgFqdn.value
$pgServerName = ($outputs | ConvertFrom-Json).properties.pgServerName.value
$acrLogin = ($outputs | ConvertFrom-Json).properties.acrLoginServer.value
$authApiUrl = ($outputs | ConvertFrom-Json).properties.authApiUrl.value
$apiGatewayUrl = ($outputs | ConvertFrom-Json).properties.apiGatewayUrl.value

Write-Host "  ✓ PostgreSQL: $pgFqdn" -ForegroundColor Green
Write-Host "  ✓ ACR: $acrLogin" -ForegroundColor Green
Write-Host "  ✓ Auth API: $authApiUrl" -ForegroundColor Green
Write-Host "  ✓ API Gateway: $apiGatewayUrl" -ForegroundColor Green

# Save outputs to env file for later use
$envContent = @"
# Generated by deploy.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
RESOURCE_GROUP=$ResourceGroup
PG_FQDN=$pgFqdn
PG_SERVER_NAME=$pgServerName
PG_PASSWORD=$pgPassword
ACR_LOGIN=$acrLogin
AUTH_API_URL=$authApiUrl
API_GATEWAY_URL=$apiGatewayUrl
"@

Set-Content -Path "$ScriptDir/.env.azure" -Value $envContent
Write-Host "  ✓ Environment vars saved to $ScriptDir/.env.azure" -ForegroundColor Green

# 6. Create PostgreSQL databases
Write-Host ""
Write-Host "[6/6] Creating PostgreSQL databases..." -ForegroundColor Yellow
$databases = @('vue_demo_auth', 'vue_demo_tasks', 'vue_demo_orders', 'vue_demo_payments')
foreach ($db in $databases) {
    Write-Host "  Creating database '$db'..." -ForegroundColor Gray
    # Use psql to create databases (requires psql installed)
    # Alternative: use Azure portal or CLI extension
    az postgres flex-db create `
        --resource-group $ResourceGroup `
        --server-name $pgServerName `
        --name $db `
        --mode Standalone `
        --admin-user vueadmin `
        --admin-password $pgPassword `
        2>$null | Out-Null
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "  ✓ Database '$db' created" -ForegroundColor Green
    } else {
        Write-Host "  ⚠ Database '$db' - may already exist or CLI extension needed (create manually)" -ForegroundColor Yellow
    }
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Infrastructure deployment complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Build Docker images: .\infra\build-images.ps1" -ForegroundColor White
Write-Host "  2. Run EF migrations: .\infra\migrate.ps1" -ForegroundColor White
Write-Host "  3. Seed auth data: az containerapp exec (auth-api)" -ForegroundColor White
Write-Host "  4. Deploy frontend: az staticwebapp deploy" -ForegroundColor White
Write-Host ""
Write-Host "⚠️  COST WARNING: Delete when done!" -ForegroundColor Red
Write-Host "   az group delete --name $ResourceGroup --yes --no-wait" -ForegroundColor Gray
