# Azure deployment script for Vue-Net-Admin-Demo
# Prerequisites: Azure CLI installed and logged in
# Usage: .\infra\deploy.ps1

$ErrorActionPreference = 'Stop'

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$BicepFile = "$ScriptDir/main.bicep"

if (-not (Test-Path -LiteralPath $BicepFile)) {
    Write-Host "ERROR: Bicep file not found at $BicepFile" -ForegroundColor Red
    exit 1
}

$ResourceGroup = 'vue-admin-rg'
$Location = 'eastus'
$DeploymentName = 'vue-admin-infra'

Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Azure Deployment: Vue-Net-Admin-Demo" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# 1. Verify login
Write-Host "[1/6] Verifying Azure login..." -ForegroundColor Yellow
az account show --query '{name:name,id:id}' | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Not logged in. Run: az login" -ForegroundColor Red
    exit 1
}

# 2. Ensure resource group exists
Write-Host "[2/6] Checking resource group..." -ForegroundColor Yellow
$rgExists = az group show --name $ResourceGroup --query id -o tsv 2>$null
if ([string]::IsNullOrWhiteSpace($rgExists)) {
    Write-Host "  Creating resource group '$ResourceGroup' in $Location..." -ForegroundColor Gray
    az group create --name $ResourceGroup --location $Location --tags Environment=dev | Out-Null
    Write-Host "  ✓ Resource group created" -ForegroundColor Green
} else {
    Write-Host "  ✓ Resource group '$ResourceGroup' exists" -ForegroundColor Green
}

# 3. Build Bicep
Write-Host "[3/6] Building Bicep template..." -ForegroundColor Yellow
az bicep build --file $BicepFile | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Bicep build failed" -ForegroundColor Red
    exit 1
}
Write-Host "  ✓ Bicep template compiled" -ForegroundColor Green

# 4. Generate secure alphanumeric password and deploy
Write-Host "[4/6] Deploying infrastructure (this takes 5-10 minutes)..." -ForegroundColor Yellow
$chars = [char[]]'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
$adminPassword = -join ($chars | Get-Random -Count 24)
$deployResult = az deployment group create `
    --resource-group $ResourceGroup `
    --name $DeploymentName `
    --template-file $BicepFile `
    --parameters "adminPassword=$adminPassword" `
    --output json `
    --only-show-errors

if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: Deployment failed" -ForegroundColor Red
    exit 1
}

# 5. Extract outputs
Write-Host "[5/6] Extracting deployment outputs..." -ForegroundColor Yellow
$outputs = $deployResult | Out-String | ConvertFrom-Json

# Outputs are nested under properties.outputs in the deployment result
$pgPassword = $adminPassword
$pgFqdn = $outputs.properties.outputs.pgFqdnOutput.value
$suffix = $outputs.properties.outputs.uniqueSuffix.value
$acrLogin = $outputs.properties.outputs.acrLoginServerOutput.value
$authApiUrl = $outputs.properties.outputs.authApiUrl.value
$apiGatewayUrl = $outputs.properties.outputs.apiGatewayUrl.value

Write-Host "  ✓ PostgreSQL FQDN: $pgFqdn" -ForegroundColor Green
Write-Host "  ✓ Suffix: $suffix" -ForegroundColor Green
Write-Host "  ✓ ACR: $acrLogin" -ForegroundColor Green
Write-Host "  ✓ Auth API: $authApiUrl" -ForegroundColor Green
Write-Host "  ✓ API Gateway: $apiGatewayUrl" -ForegroundColor Green

# Save outputs to env file for later use
$envContent = @"
# Generated by deploy.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
RESOURCE_GROUP=$ResourceGroup
PG_FQDN=$pgFqdn
PG_PASSWORD=$pgPassword
UNIQUE_SUFFIX=$suffix
ACR_LOGIN=$acrLogin
AUTH_API_URL=$authApiUrl
API_GATEWAY_URL=$apiGatewayUrl
"@

$envFile = "$ScriptDir/.env.azure"
Set-Content -Path $envFile -Value $envContent
Write-Host "  ✓ Environment vars saved to $envFile" -ForegroundColor Green

# 6. Verify PostgreSQL is running
Write-Host ""
Write-Host "[6/6] Verifying PostgreSQL deployment..." -ForegroundColor Yellow
$pgContainerName = "postgresql-${suffix}"

Write-Host "  Waiting for PostgreSQL container to be ready..." -ForegroundColor Gray
$ready = $false
$maxRetries = 30
$retryCount = 0
while (-not $ready -and $retryCount -lt $maxRetries) {
    $state = az containerapp show `
        --name $pgContainerName `
        --resource-group $ResourceGroup `
        --query "properties.latestRevisionFqdn" `
        -o tsv 2>$null
    if ($state) { $ready = $true }
    else {
        $retryCount++
        Start-Sleep -Seconds 10
    }
}

if (-not $ready) {
    Write-Host "  ⚠ PostgreSQL container not ready within 5 min." -ForegroundColor Yellow
} else {
    Write-Host "  ✓ PostgreSQL container is ready" -ForegroundColor Green
    Write-Host "  ℹ Database 'vue_demo_auth' auto-created by POSTGRES_DB env var." -ForegroundColor Gray
    Write-Host "  ℹ Other databases (vue_demo_tasks, vue_demo_orders, vue_demo_payments)" -ForegroundColor Gray
    Write-Host "    will be created on first EF Core migration via each service's" -ForegroundColor Gray
    Write-Host "    startup initializer. See .infra/migrate.ps1." -ForegroundColor Gray
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Infrastructure deployment complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Build Docker images: .\infra\build-images.ps1" -ForegroundColor White
Write-Host "  2. Run EF migrations: .\infra\migrate.ps1" -ForegroundColor White
Write-Host "  3. Seed auth data: az containerapp exec (auth-api)" -ForegroundColor White
Write-Host "  4. Deploy frontend: az staticwebapp deploy" -ForegroundColor White
Write-Host ""
Write-Host "⚠️  COST WARNING: Delete when done!" -ForegroundColor Red
Write-Host "   az group delete --name $ResourceGroup --yes --no-wait" -ForegroundColor Gray
